// Code generated by mockery v2.43.2. DO NOT EDIT.

package multiraft

import mock "github.com/stretchr/testify/mock"

// MockRaftAdder is an autogenerated mock type for the RaftAdder type
type MockRaftAdder struct {
	mock.Mock
}

// addRaft provides a mock function with given fields: id
func (_m *MockRaftAdder) addRaft(id uint32) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for addRaft")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint32) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockRaftAdder creates a new instance of MockRaftAdder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRaftAdder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRaftAdder {
	mock := &MockRaftAdder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
