// Code generated by deep-copy -o transport_header.deepcopy.go --pointer-receiver --type RaftRPCHeader .; DO NOT EDIT.

package transport

// DeepCopy generates a deep copy of *RaftRPCHeader
func (o *RaftRPCHeader) DeepCopy() *RaftRPCHeader {
	var cp RaftRPCHeader = *o
	if o.RPCHeader.ID != nil {
		cp.RPCHeader.ID = make([]byte, len(o.RPCHeader.ID))
		copy(cp.RPCHeader.ID, o.RPCHeader.ID)
	}
	if o.RPCHeader.Addr != nil {
		cp.RPCHeader.Addr = make([]byte, len(o.RPCHeader.Addr))
		copy(cp.RPCHeader.Addr, o.RPCHeader.Addr)
	}
	if o.RPCHeader.Meta != nil {
		cp.RPCHeader.Meta = make(map[string]interface{}, len(o.RPCHeader.Meta))
		for k3, v3 := range o.RPCHeader.Meta {
			cp.RPCHeader.Meta[k3] = v3
		}
	}
	return &cp
}
