// Code generated by deep-copy -o RequestVoteRequest.deepcopy.go --pointer-receiver --type RequestVoteRequest .; DO NOT EDIT.

package requests

import (
	"github.com/dhiaayachi/raft"
)

// DeepCopy generates a deep copy of *RequestVoteRequest
func (o *RequestVoteRequest) DeepCopy() *RequestVoteRequest {
	var cp RequestVoteRequest = *o
	if o.RequestVoteRequest != nil {
		cp.RequestVoteRequest = new(raft.RequestVoteRequest)
		*cp.RequestVoteRequest = *o.RequestVoteRequest
		if o.RequestVoteRequest.RPCHeader.ID != nil {
			cp.RequestVoteRequest.RPCHeader.ID = make([]byte, len(o.RequestVoteRequest.RPCHeader.ID))
			copy(cp.RequestVoteRequest.RPCHeader.ID, o.RequestVoteRequest.RPCHeader.ID)
		}
		if o.RequestVoteRequest.RPCHeader.Addr != nil {
			cp.RequestVoteRequest.RPCHeader.Addr = make([]byte, len(o.RequestVoteRequest.RPCHeader.Addr))
			copy(cp.RequestVoteRequest.RPCHeader.Addr, o.RequestVoteRequest.RPCHeader.Addr)
		}
		if o.RequestVoteRequest.RPCHeader.Meta != nil {
			cp.RequestVoteRequest.RPCHeader.Meta = make(map[string]any, len(o.RequestVoteRequest.RPCHeader.Meta))
			for k5, v5 := range o.RequestVoteRequest.RPCHeader.Meta {
				cp.RequestVoteRequest.RPCHeader.Meta[k5] = v5
			}
		}
		if o.RequestVoteRequest.Candidate != nil {
			cp.RequestVoteRequest.Candidate = make([]byte, len(o.RequestVoteRequest.Candidate))
			copy(cp.RequestVoteRequest.Candidate, o.RequestVoteRequest.Candidate)
		}
	}
	return &cp
}
