// Code generated by deep-copy -o TimeoutNowRequest.deepcopy.go --pointer-receiver --type TimeoutNowRequest .; DO NOT EDIT.

package requests

import (
	"github.com/hashicorp/raft"
)

// DeepCopy generates a deep copy of *TimeoutNowRequest
func (o *TimeoutNowRequest) DeepCopy() *TimeoutNowRequest {
	var cp TimeoutNowRequest = *o
	if o.TimeoutNowRequest != nil {
		cp.TimeoutNowRequest = new(raft.TimeoutNowRequest)
		*cp.TimeoutNowRequest = *o.TimeoutNowRequest
		if o.TimeoutNowRequest.RPCHeader.ID != nil {
			cp.TimeoutNowRequest.RPCHeader.ID = make([]byte, len(o.TimeoutNowRequest.RPCHeader.ID))
			copy(cp.TimeoutNowRequest.RPCHeader.ID, o.TimeoutNowRequest.RPCHeader.ID)
		}
		if o.TimeoutNowRequest.RPCHeader.Addr != nil {
			cp.TimeoutNowRequest.RPCHeader.Addr = make([]byte, len(o.TimeoutNowRequest.RPCHeader.Addr))
			copy(cp.TimeoutNowRequest.RPCHeader.Addr, o.TimeoutNowRequest.RPCHeader.Addr)
		}
		if o.TimeoutNowRequest.RPCHeader.Meta != nil {
			cp.TimeoutNowRequest.RPCHeader.Meta = make(map[string]any, len(o.TimeoutNowRequest.RPCHeader.Meta))
			for k5, v5 := range o.TimeoutNowRequest.RPCHeader.Meta {
				cp.TimeoutNowRequest.RPCHeader.Meta[k5] = v5
			}
		}
	}
	return &cp
}
