name: Go
on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-action@v1
        with:
          push: false
      - name: Check if buf changes
        run: git diff --quiet || false
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.1'
      - name: Install dependencies
        run: go mod tidy

      - name: Build
        run: go build -v ./...
      - name: Test with the Go CLI
        run: go test -race ./...